name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
      fail-fast: false 

    steps:
      - uses: actions/checkout@v3
      
      - name: Setup PowerShell
        uses: actions/setup-powershell@v3  
        with:
          version: '7.4.0'
      
      - name: Install dependencies
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            sudo apt-get update && sudo apt-get install -y p7zip-full
          else
            choco install -y 7zip.install  # Исправлено: 7zip → 7zip.install
          fi
      
      - name: Install Pester
        shell: pwsh
        run: Install-Module -Name Pester -Force -Scope CurrentUser
      
      - name: Build and test
        shell: pwsh
        run: |
          ./Create-Artifacts.ps1
          Invoke-Pester ./tests/Artifacts.Tests.ps1