name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PowerShell on Linux
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y wget apt-transport-https software-properties-common p7zip-full
          wget -q "https://packages.microsoft.com/config/ubuntu/22.04/packages-microsoft-prod.deb"
          sudo dpkg -i packages-microsoft-prod.deb
          sudo apt-get update
          sudo apt-get install -y powershell
        shell: bash

      - name: Setup PowerShell on Windows
        if: runner.os == 'Windows'
        run: choco install powershell --version=7.4.0 -y --force
        shell: powershell

      - name: Install Pester
        shell: pwsh
        run: |
          Install-Module -Name Pester -Force -Scope CurrentUser -AllowClobber -SkipPublisherCheck

      - name: Build and test
        shell: pwsh
        run: |
          $ErrorActionPreference = 'Stop'

          # упаковываем
          .\Create-Artifacts.ps1 -RootDir './dev_build'

          # запускаем тесты
          $testResults = Join-Path $env:GITHUB_WORKSPACE 'test-results.xml'
          Invoke-Pester './tests/Artifacts.Tests.ps1' `
            -OutputFile $testResults -OutputFormat NUnitXml

          Write-Host '✅ Все тесты прошли успешно'
